title: Settings
data:
  site_name: 'Marcos Bonifaz'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/jackmcdade'
      icon: site/social-icons/twitter.svg
    -
      name: Email
      url: 'mailto:jack@statamic.com'
      icon: site/social-icons/email.svg
